### ISSUE TITLE
RCON is broken

### ISSUE THREAD

**Issue by chazzanichols** [LoomDev/Loom#31]
Hi, as the title suggests I've tried connecting to my Loom server via RCON and it works fine until I send a command, at which point I get the following error:
```
Exception in thread "main" com.github.t9t.minecraftrconclient.RconClientException: Expected 4 bytes received -1
        at com.github.t9t.minecraftrconclient.RconClient.readData(RconClient.java:122)
        at com.github.t9t.minecraftrconclient.RconClient.readResponse(RconClient.java:98)
        at com.github.t9t.minecraftrconclient.RconClient.send(RconClient.java:78)
        at com.github.t9t.minecraftrconclient.RconClient.sendCommand(RconClient.java:52)
        at com.github.t9t.minecraftrconclient.RconClientCli.run(RconClientCli.java:59)
        at com.github.t9t.minecraftrconclient.RconClientCli.main(RconClientCli.java:17)
```
I've tried connecting to and running commands on a vanilla sever and it seems ok.

**Comment by nkomarn** [comment]
Are there any errors in the Loom server console?

**Comment by chazzanichols** [comment]
Here's the relevant part of the log:
```
[09:45:01 INFO]: Preparing spawn area: 92%
[09:45:01 INFO]: Time elapsed: 7156 ms
[09:45:01 INFO]: Done (7.262s)! For help, type "help"
[09:45:01 INFO]: Starting remote control listener [09:45:01 INFO]: Thread RCON Listener started
[09:45:01 INFO]: RCON running on 0.0.0.0:25575 [09:46:14 INFO]: Thread RCON Client /127.0.0.1 started
[09:46:14 INFO]: Thread RCON Client /127.0.0.1 shutting down
[09:46:14 INFO]: Thread RCON Client /127.0.0.1 shutting down
```
It immediately shuts down after connecting, but the client terminal still shows it being connected.

**Comment by chazzanichols** [comment]
I semi-fixed the issue by modifying the source code and stopping the server from closing the socket.
I commented out the lines 110 to 112 in the RconClient.java file and it works for now.
